version: "3.8"

#Docker Networks
networks:
  csproject:
    driver: bridge
    external: true

#Volumes
volumes:
  dbdata:
    driver: local
  notifications-api-data:
    name: notifications-api-data
  rabbitmq_data:
    driver: local

  # Workflow
services:
  notifications_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: notifications_api
    ports:
      - 8083:80
    volumes:
      - .:/var/www/html
    depends_on:
      - notifications_rabbitmq
    networks:
      - csproject

  notifications_rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672" # Expose the management UI
      - "5672:5672"   # Expose the AMQP port
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - csproject